[project]
name = "chunking"
version = "0.1.0"
description = "A project to evaluate the performance of chunking techniques at scale"
authors = [
    "anonymous"
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "basemap>=2.0.0",
    "click>=8.3.0",
    "datasets>=4.2.0",
    "dotenv>=0.9.9",
    "faiss-cpu>=1.12.0",
    "huggingface-hub>=0.35.3",
    "iscc-core>=1.2.2",
    "llama-index==0.14.6",
    "llama-index-embeddings-huggingface>=0.6.1",
    "matplotlib>=3.10.8",
    "openai>=1.109.1",
    "pytrec-eval-terrier>=0.5.10",
    "statsmodels>=0.14.6",
    "torch>=2.9.0",
    "tqdm>=4.67.1",
    "tqdm-joblib>=0.0.5",
    "transformers>=4.57.1",
]
